### ISSUE TITLE
What are benefits?

### ISSUE THREAD

**Issue by seongbae-ml** [chrisguitarguy/wordpress-skeleton#1]
What are benefits of using Composer to manage Wordpress?

**Comment by chrisguitarguy** [comment]
The biggest one, to me, is having access to the entire world of PHP libraries on packagist without having do something crazy like submodule them or copy them.

Other than that:
- Reducing repo size (third party code is hidden behind the dependency management system), it's not in the repo as a submodule or static files.
- Explicit [declaration of dependencies](http://12factor.net/dependencies).
- Forces you to think differently than hacking on existing plugins (because your changes will be killed on the next `composer update`.
